### ISSUE TITLE
Bits in missing/v2 depend on missingo/v1

### ISSUE THREAD

**Issue by yarikk** [anacrolix/missinggo#19]
Having multi-version internal dependencies, along spoiling the style, breaks vendoring.

The library should be made consistent on which version of sub-packages they depend on.

**Comment by anacrolix** [comment]
I think I intend to use the major versioning provided by Go modules, such that it is, for most of my projects. I should have broken out submodules rather than moving the root module in this repo to v2, I'm undecided about how to proceed from its current state.

**Comment by anacrolix** [comment]
Debian, and a few other downstream projects have found the monolithic nature of this repo to be a nuisance, so there's some pressure to break it up, at least into submodules or into new repos. Several of the packages are only used by some consumers, and probably should have been internal to them rather than stockpiled here.

**Comment by anacrolix** [comment]
I'll close this, the fix is to break up the entire module, or not depend on it. Let me know if you still have the issue @yarikk but I think everyone is moving to Go modules now so I suspect it's not an issue for you anymore.
